### ISSUE TITLE
"out of memory" in the go client

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline-issues#452]
BrailleNet recently switched to the go client. Since that time, we can get "out of memory" errors on big books, right before terminating the current job.

Perhaps zipping the output directory was making a noticeable difference for the Ruby client.
Is there any option to configure the way the output directory is handled in local mode?

Full stack:
```
(8897)[INFO]	Copied part0159_00_000.mp3 to part0159_00_000.mp3
(8898)[INFO]	Copied part3830_00_000.mp3 to part3830_00_000.mp3
(8899)[INFO]	Writing in-memory document to resources.res
(8900)[INFO]	Writing in-memory document to book.opf

runtime: memory allocated by OS (0xb755d000) not in usable range [0x18900000,0x98900000)
runtime: out of memory: cannot allocate 1073741824-byte block (1088880640 in use)
fatal error: out of memory

goroutine 1 [running]:
runtime.throw(0x8625797)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/panic.c:464 +0x68 fp=0xf76bf248
runtime.mallocgc(0x3ffffe00, 0x825f5e1, 0x1)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/malloc.goc:91 +0x415 fp=0xf76bf284
cnew(0x825f5e0, 0x3ffffe00, 0x1)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/malloc.goc:718 +0xaa fp=0xf76bf294
runtime.cnewarray(0x825f5e0, 0x3ffffe00)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/malloc.goc:731 +0x3c fp=0xf76bf2a4
makeslice1(0x8255820, 0x3ffffe00, 0x3ffffe00, 0xf76bf2e4)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/slice.c:57 +0x48 fp=0xf76bf2b0
runtime.makeslice(0x8255820, 0x3ffffe00, 0x0, 0x3ffffe00, 0x0, ...)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/slice.c:38 +0x97 fp=0xf76bf2d0
bytes.makeSlice(0x3ffffe00, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/bytes/buffer.go:191 +0x6f fp=0xf76bf2f4
bytes.(*Buffer).ReadFrom(0x18a505a0, 0xf77accf0, 0x189d1b10, 0x1ffffe00, 0x0, ...)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/bytes/buffer.go:163 +0xab fp=0xf76bf334
io/ioutil.readAll(0xf77accf0, 0x189d1b10, 0x200, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/io/ioutil/ioutil.go:32 +0x114 fp=0xf76bf37c
io/ioutil.ReadAll(0xf77accf0, 0x189d1b10, 0x189d1b10, 0xf77accf0, 0x189d1b10, ...)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/io/ioutil/ioutil.go:41 +0x43 fp=0xf76bf3a4
github.com/capitancambio/restclient.(*Client).Do(0x18a52220, 0x18a50480, 0xc8, 0x0, 0x0)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/restclient/client.go:206 +0x932 fp=0xf76bf58c
github.com/daisy/pipeline-clientlib-go.Pipeline.do(0x1896dba0, 0x19, 0x195dcf58, 0x836c5fc, 0x18a50480, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-clientlib-go/doer.go:125 +0x6f fp=0xf76bf60c
github.com/daisy/pipeline-clientlib-go.Pipeline.Results(0x1896dba0, 0x19, 0x195dcf58, 0x836c5fc, 0x189abf00, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-clientlib-go/pipeline.go:215 +0x206 fp=0xf76bf670
github.com/daisy/pipeline-clientlib-go.(*Pipeline).Results(0x18942740, 0x189abf00, 0x24, 0x0, 0x0, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-clientlib-go/doer.go:1 +0xa9 fp=0xf76bf6a0
github.com/daisy/pipeline-cli-go/cli.PipelineLink.Results(0xf77aaae0, 0x18942740, 0x1891cd00, 0x18942be0, 0xc, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/link.go:137 +0x67 fp=0xf76bf6c4
github.com/daisy/pipeline-cli-go/cli.jobExecution.run(0x1896d160, 0x1898a810, 0xff899376, 0x26, 0x1, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/scripts.go:100 +0x5b1 fp=0xf76bf9a4
github.com/daisy/pipeline-cli-go/cli.func·045(0x1898b8a0, 0x10, 0x0, 0x0, 0x0, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/scripts.go:138 +0x46 fp=0xf76bf9cc
github.com/capitancambio/go-subcommand.Command.exec(0x1898b8a0, 0x10, 0x18989cc0, 0x3d, 0x18985360, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/go-subcommand/parser.go:164 +0x412 fp=0xf76bfb7c
github.com/capitancambio/go-subcommand.(*Parser).parse(0x1890e280, 0x1890a010, 0x8, 0x8, 0x1898b8a0, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/go-subcommand/parser.go:140 +0x68d fp=0xf76bfcd8
github.com/capitancambio/go-subcommand.func·005(0x82ea888, 0x3)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/go-subcommand/parser.go:118 +0xab fp=0xf76bfd48
github.com/capitancambio/go-subcommand.(*Parser).parse(0x1890e280, 0x1890a008, 0x9, 0x9, 0x82ea888, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/go-subcommand/parser.go:145 +0x6cb fp=0xf76bfea4
github.com/capitancambio/go-subcommand.(*Parser).Parse(0x1890e280, 0x1890a008, 0x9, 0x9, 0x0, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/capitancambio/go-subcommand/parser.go:74 +0x7c fp=0xf76bfefc
github.com/daisy/pipeline-cli-go/cli.(*Cli).Run(0x1891de40, 0x1890a008, 0x9, 0x9, 0x0, ...)
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/cli.go:228 +0x45 fp=0xf76bff24
main.main()
	/Users/Romain/Work/daisy-pipeline/go/pipeline-cli-go/dp2/dp2.go:53 +0x4a3 fp=0xf76bff98
runtime.main()
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:220 +0x111 fp=0xf76bffcc
runtime.goexit()
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:1394 fp=0xf76bffd0

goroutine 4 [finalizer wait]:
runtime.park(0x80516f0, 0x8627c0c, 0x8626368)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:1342 +0x65
runfinq()
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/mgc0.c:2279 +0x7b
runtime.goexit()
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:1394

goroutine 6 [chan receive]:
net/http.(*persistConn).readLoop(0x1896e410)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/transport.go:778 +0x51e
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/transport.go:528 +0x4c7

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0x1896e410)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/transport.go:791 +0x207
created by net/http.(*Transport).dialConn
```

**Comment by capitancambio** [comment]
So in the last release we included the -z option to get the zipped version rather than inflating it. It wasn't really perfomant though, I've refactored some parts of the cli and the library improve this issue, I was able to transfer a a 5.5GB file hands down. :smile: . Even though I also improved the inflating logic it still might be more prone to out of memory errors

Enjoy!

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-cli-go/commit/72d934acd8fb7a88069ac2eea1f33f37451e11db
