### ISSUE TITLE
Webservice doesn't stop with the custom laucher is used instead of felix default.

### ISSUE THREAD

**Issue by capitancambio** [daisy/pipeline-issues#469]
calling ./dp2 halt sends the halt signal to the webservice but it fails to stop the process. When interacting with the gogo shell this is the output:

```
g! lb
gosh: java.lang.IllegalStateException: session is closed
gosh: stopping framework
gogo: IllegalStateException: Invalid BundleContext.
java.lang.IllegalStateException: Invalid BundleContext.
        at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:514)
        at org.apache.felix.framework.BundleContextImpl.getBundle(BundleContextImpl.java:173)
        at org.apache.felix.gogo.shell.Shell.shutdown(Shell.java:183)
        at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
        at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:92)
        at org.apache.felix.gogo.shell.Activator.run(Activator.java:75)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by capitancambio** [comment]
This is fixed after the changes in the javafx branches
