### ISSUE TITLE
A 500 error when no log is gernerated

### ISSUE THREAD

**Issue by capitancambio** [daisy/pipeline-issues#472]
It should be a 404?

this is the error:

<?xml version="1.0" encoding="UTF-8" standalone="no"?><error query="http://localhost:8181/ws/jobs/3764599a-027d-424f-a97c-4c025797a910/log?authid=clientid&amp;time=2015-11-24T17:30:14Z&amp;nonce=154668735570092530936984968962&amp;sign=aX6wiN6LEyl8JCoSa0SdK3%2BEcqE=" xmlns="http://www.daisy.org/ns/pipeline/data"><description>Internal Server Error</description><trace>Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:517)
	at org.restlet.resource.ServerResource.get(ServerResource.java:707)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:589)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:649)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:951)
	at org.restlet.resource.Finder.handle(Finder.java:246)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:431)
	at org.restlet.routing.Router.handle(Router.java:648)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
	at org.restlet.Application.handle(Application.java:381)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:431)
	at org.restlet.routing.Router.handle(Router.java:648)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:431)
	at org.restlet.routing.Router.handle(Router.java:648)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
	at org.restlet.Component.handle(Component.java:392)
	at org.restlet.Server.handle(Server.java:516)
	at org.restlet.engine.connector.ServerConnectionHelper.handle(ServerConnectionHelper.java:254)
	at org.restlet.engine.connector.ServerConnectionHelper.doHandleInbound(ServerConnectionHelper.java:186)
	at org.restlet.engine.connector.BaseHelper$2.run(BaseHelper.java:588)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.common.base.Absent.get(Absent.java:42)
	at org.daisy.pipeline.webservice.impl.LogResource.getResource(LogResource.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:506)
	... 44 more
</trace></error>

**Comment by josteinaj** [comment]
All jobs should have a log though, shouldn't they? A 404 would be if you try requesting a log from a non-existing job?

**Comment by capitancambio** [comment]
Internally, the job won't have a log until it starts executing. The job I launched never started so the actual file was missing, in this case I presume that downloading an empty log should do the trick

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-framework/pull/98
